# Generated by Django 2.2 on 2020-05-04 22:54

from django.db import migrations, models
import django.db.models.deletion
import online_lending.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=512)),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('need_money_for', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('user_role', models.IntegerField(choices=[(online_lending.models.UserRole(0), 0), (online_lending.models.UserRole(1), 1), (online_lending.models.UserRole(2), 2)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='online_lending.User')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='online_lending.User')),
            ],
        ),
    ]
